# Generated by Django 3.2.8 on 2022-10-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказ')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.brand', verbose_name='Марка авто')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.car', verbose_name='Модель авто')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.color', verbose_name='Цвет')),
            ],
        ),
    ]
