# Generated by Django 3.2.8 on 2022-10-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
    ]
